[package]
name = "operations"
version = "0.1.2"
edition = "2021"
license = "MIT"
description = "Basic algebraic and mathematical expressions for use with dynamic elements"

[dependencies]
num-traits = "0.2.15"
ndarray = "0.15.6"
nalgebra = "0.32.3"